// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xegmschlynjllyybaijq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlZ21zY2hseW5qbGx5eWJhaWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDE1NjMsImV4cCI6MjA2NzgxNzU2M30.yrjZnioBmtk35sAiS1PPGv0CUS2AL0mzX1thVsMWIUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});